### ISSUE TITLE
Bchron issue with multiple dating methods

### ISSUE THREAD

**Issue by Danmiller09** [nickmckay/GeoChronR#22]
Currently you cannot select more than one calibration, which is an issue if you use multiple types of ages (C14 and cs-137, etc..).  You can only select "intcal13" or "normal", not both like you can if you run Bchron separately. I also tried separating the dating types into different tables, but received an error when trying to use both tables.

**Comment by nickmckay** [comment]
Thanks Dan. We (@khider) will look into it!
