### ISSUE TITLE
problem with plotSummary

### ISSUE THREAD

**Issue by ebroadman** [nickmckay/GeoChronR#28]
When I try to use "plotSummary" I end up with this error:

Warning: bounding box given to google - spatial extent only approximate.
converting bounding box to center/zoom specification. (experimental)
Error in download.file(url, destfile = tmp, quiet = !messaging, mode = "wb") : 
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=60.596167,-150.877917&zoom=5&size=640x640&scale=2&maptype=terrain&language=en-EN&sensor=false'

And the same thing happened when I tried "mapLipd". Any thoughts? Thanks!

**Comment by nickmckay** [comment]
Yep,

I replicated this. It seems like it's a google issue, here's what the URL
resolves too:

"The Google Maps Platform server rejected your request. You must use an API
key to authenticate each request to Google Maps Platform APIs. For
additional information, please refer to http://g.co/dev/maps-no-account"

And from Google's FAQ:


I’ve been making API calls without a key

I’m using APIs for free or without a key. Can I keep doing this?

You must have a valid API key and a billing account to access our APIs.
When you enable billing, you will get $200 free usage every month for Maps,
Routes, or Places. Based on the millions of users using our APIs today,
most of them can continue to use Google Maps Platform for free with this
credit. Having a billing account helps us understand our developers’ needs
better and allows you to scale seamlessly.

I'll look into this, but this may be the end for google maps in GeoChronR.
There are alternatives.

**Comment by nickmckay** [comment]
OK, I changed the default behaviour to use stamen maps, instead of google maps. This is a little unsatisfying, but should work. Will work on improving this. Line maps should still work as usual.
