### ISSUE TITLE
Problem with extractTs

### ISSUE THREAD

**Issue by georgyfalster** [nickmckay/GeoChronR#29]
I've been trying to create timeseries from an object ('sites') with three LiPDs, after running mapAgeEnsembleToPaleoData(). I get the following error:

> TS <- extractTs(sites)
Error in current[[nameToUse]] <- table_data[[sc]]$values : 
  attempt to select less than one element in OneIndex

I've looked at the data using plotTimeseriesEnsRibbons() and it's all loaded fine.

**Comment by nickmckay** [comment]
I'm almost sure that @georgyfalster and I resolved this and it's fixed now, but let me know if I'm wrong
