### ISSUE TITLE
easy way to flip y-axes in plotTimeseriesStack?

### ISSUE THREAD

**Issue by ebroadman** [nickmckay/GeoChronR#30]
I am creating stacked plots with several times series, some of which need their y-axes flipped (values in reverse order). It would be awesome if there was an easy way to specify this when using plotTimeseriesStack...

**Comment by sarcusa** [comment]
Is a solution to this question already available?

**Comment by sarcusa** [comment]
Is a solution available for this question?

**Comment by nickmckay** [comment]
Feature added in version 1.0.5. Details [in the changelog](http://nickmckay.github.io/GeoChronR/news/index.html).
