### ISSUE TITLE
Cannot load .lpd files downloaded from the wiki.

### ISSUE THREAD

**Issue by gelasher** [nickmckay/GeoChronR#31]
Tried to load the Arc-Dye.Vinther.2010.lpd file and received:
"Error: import_model: Error in \"index_col_by_name: \" + cond: non-numeric argument to binary operator\n"

**Comment by nickmckay** [comment]
Do you have the most recent versions of lipdR and geoChronR installed? Is
this the Arc-Dye.Vinther.2010.lpd file that comes with the package? If not,
where was it downloaded from?

Cheers,
Nick

**Comment by gelasher** [comment]
Yes, just updated using the devtools. I downloaded the Arc-Dye.Vinther.2010.lpd file from the wiki... (http://wiki.linked.earth/Arc-Dye.Vinther.2010) I did not use the one that comes with the package.

**Comment by chrismheiser** [comment]
Closing the issue since this is a problem with how the wiki is building the LiPD file.
