### ISSUE TITLE
GeoGhronR Installation Error

### ISSUE THREAD

**Issue by jordahle** [nickmckay/GeoChronR#42]
Good Morning, 

I am very excited to get into working with GeoChronR, but I am having some issues with installation. The two extra packages downloads went perfectly well, but I am receiving this error when attempting to install the main package.

##
remotes::install_github("nickmckay/geoChronR")
checking for file 
preparing 'geoChronR': (1m 4.9s)
checking DESCRIPTION meta-information (502ms)
E  checking vignette meta-information (2.5s)
   Output(s) listed in 'build/vignette.rds' but not in package:
     'inst/doc/Introduction.html'
     'inst/doc/PCA.html'
     'inst/doc/PlotTimeseriesStack.html'
     'inst/doc/TsFilteringAndMapping.html'
     'inst/doc/correlation.html'
     'inst/doc/oxCal.html'
     'inst/doc/regression.html'
     'inst/doc/spectral_analysis.html'
   Run R CMD build without --no-build-vignettes to re-create
Error: Failed to install 'geoChronR' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Output(s) listed in 'build/vignette.rds' but not in package:
E>   'inst/doc/Introduction.html'
E>   'inst/doc/PCA.html'
E>   'inst/doc/PlotTimeseriesStack.html'
E>   'inst/doc/TsFilteringAndMapping.html'
E>   'inst/doc/correlation.html'
E>   'inst/doc/oxCal.html'
E>   'inst/doc/regression.html'
E>   'inst/doc/spectral_analysis.html'
E> Run R CMD build without --no-build-vignettes to re-create
##

This is likely not an issue with the package, but you likely have the most experience troubleshooting the installation of this package. I have tried to install with building vignettes, but errors also occur. 

##
Error: Failed to install 'geoChronR' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E>  97 2663k   97 2603k    0     0  1301k      0  0:00:02  0:00:02 --:--:-- 1022k
E> 100 2663k  100 2663k    0     0  1331k      0  0:00:02  0:00:02 --:--:-- 1039k
E> --- finished re-building 'spectral_analysis.Rmd'
E> 
E> SUMMARY: processing the following files failed:
E>   'Introduction.Rmd' 'PCA.Rmd' 'TsFilteringAndMapping.Rmd'
E>   'correlation.Rmd' 'oxCal.Rmd' 'regression.Rmd'
E> 
E> Error: Vignette re-building failed.
E> Execution halted
##

**Comment by nickmckay** [comment]
Thank you for reporting this. Looks like there was an error with the vignette installation. I pushed an update and tested on a Windows computer. Try it again and let me know if you still have issues.

**Comment by jordahle** [comment]
Thank you for the quick response! Looks like it worked!

**Comment by nickmckay** [comment]
Great! Please let us know if you run into bugs, issues or have feature requests!
