### ISSUE TITLE
mapTs basemap not plotting properly

### ISSUE THREAD

**Issue by sarcusa** [nickmckay/GeoChronR#43]
I am using the function mapTs to plot the location of a filtered and queried list of LiPD objects. The baseplot doesn't not plot well with horizontal lines running across the globe. See image below.

![image](https://user-images.githubusercontent.com/25307765/94322441-72ae2e00-ff47-11ea-918b-bb88eae8ecee.png)

**Comment by nickmckay** [comment]
This is a parameter issue. Better default parameter detection added in [version 1.0.4](https://nickmckay.github.io/GeoChronR/news/index.html)
