### ISSUE TITLE
tidyTs fails: paleoData_values didn't show up as being the longest vector

### ISSUE THREAD

**Issue by sarcusa** [nickmckay/GeoChronR#44]
I would like to use the function tidyTs on a filtered and queried TS but I get the following error:

TS_EX = filterTs(data_EX, 'useEX == 1') 
interps <- pullTsVariable(TS = TS_EX,variable = "interpretation1_variable")
index <- which(interps == 'M' | interps == 'P' | interps == 'P-E' | interps ==  'P/E')
TS_EX_M <- TS_EX[index]

> tidy.M <- tidyTs(TS_EX_M)
  |                                                                             |   0%[1] "Tidying your  78  timeseries"
  |=                                                                            |   1%
Error in tidyTs(TS_EX_M) : 
  1: paleoData_values didn't show up as being the longest vector
>

**Comment by nickmckay** [comment]
This was an out of date lipdR package issue
