### ISSUE TITLE
tidyTs fails: Error in set(tidyData, i = sr:er, j = nm, tdf) : Cannot assign 'factor' to 'double'.

### ISSUE THREAD

**Issue by sarcusa** [nickmckay/GeoChronR#45]
I would like to use the function tidyTs but I get the following error:

TS_EX = filterTs(data_EX, 'useEX == 1') 
interps <- pullTsVariable(TS = TS_EX,variable = "interpretation1_variable")
index <- which(interps == 'T' | interps == 'TM')
TS_EX_T <- TS_EX[index]

> tidy.T <- tidyTs(TS_EX_T)
  |                                                                             |   0%[1] "Tidying your  76  timeseries"
  |=                                                                            |   1%
Error in set(tidyData, i = sr:er, j = nm, tdf) : 
  Cannot assign 'factor' to 'double'. Factors can only be assigned to factor, character or list columns.
>

**Comment by nickmckay** [comment]
This was an out of date lipdR package issue
