### ISSUE TITLE
Ensemble PCA tutorial; mapLipd error

### ISSUE THREAD

**Issue by istvan60** [nickmckay/GeoChronR#46]
Dear Developers,

I tried to run the Ensemble PCA tutorial from https://nickmckay.github.io/GeoChronR/articles/PCA.html loaded the packages and the data, but when trying to plot them I got the error:

> mapLipd(FD,map.type = "line",projection = "stereo",f = 0.1)
Error in mapLipd(FD, map.type = "line", projection = "stereo", f = 0.1) : 
  unused arguments (projection = "stereo", f = 0.1)

When loading a different set of Lipd files taken from the iso2k database I get the same error.

Without the stereo projection setting the following error pops up in the case of any Lipd file:
> mapLipd(FD,map.type = "line")
Error in mapgetg(database, gon, as.polygon, xlim, ylim) : 
  NA/NaN/Inf in foreign function call (arg 6)

When loading a different set of Lipd files taken from the iso2k database I get the same error.
I suppose there is probably an issue with how the lat and lon coordinates are be constructed.

Thank you for the help!

**Comment by nickmckay** [comment]
It seems like you may have an outdated version of geoChronR installed. Will you check 
`packageVersion("geoChronR")`

The current version is 1.0.4, which you can update using

`remotes::install_github("nickmckay/GeoChronR")`

If you're already at the current version, let me know and I'll keep digging.

**Comment by istvan60** [comment]
It is indeed an outdated version, and I am starting to feel silly because when updating the following error popped up:

> packageVersion("geoChronR")
[1] ‘0.3’
> remotes::install_github("nickmckay/GeoChronR")
Downloading GitHub repo nickmckay/GeoChronR@HEAD
✓  checking for file ‘/private/var/folders/wz/tjjypv1n1hx5zhd8w2cdzr880000gn/T/RtmpxUCznX/remotes173425c63faf8/nickmckay-GeoChronR-8aa49c5/DESCRIPTION’ ...
─  preparing ‘geoChronR’: (1.5s)
✓  checking DESCRIPTION meta-information ...
E  checking vignette meta-information ...
   Output(s) listed in ‘build/vignette.rds’ but not in package:
     ‘inst/doc/Introduction.html’
     ‘inst/doc/PCA.html’
     ‘inst/doc/PlotTimeseriesStack.html’
     ‘inst/doc/TsFilteringAndMapping.html’
     ‘inst/doc/correlation.html’
     ‘inst/doc/oxCal.html’
     ‘inst/doc/regression.html’
     ‘inst/doc/spectral_analysis.html’
   Run R CMD build without --no-build-vignettes to re-create
Error: Failed to install 'geoChronR' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Output(s) listed in ‘build/vignette.rds’ but not in package:
E>   ‘inst/doc/Introduction.html’
E>   ‘inst/doc/PCA.html’
E>   ‘inst/doc/PlotTimeseriesStack.html’
E>   ‘inst/doc/TsFilteringAndMapping.html’
E>   ‘inst/doc/correlation.html’
E>   ‘inst/doc/oxCal.html’
E>   ‘inst/doc/regression.html’
E>   ‘inst/doc/spectral_analysis.html’
E> Run R CMD build without --no-build-vignettes to re-create
> packageVersion("geoChronR")
[1] ‘0.3’

So no update was performed, and I haven't got the slightest idea why. If I am the clumsy one please ignore the issue, but I suppose it should be working....

**Comment by nickmckay** [comment]
Ah, that looks like my fault. I think it's fixed now, but let me know if you have issues.

**Comment by istvan60** [comment]
Now it works like a charm, thanks!
