### ISSUE TITLE
Weird behavior with single instance in group.var variable in plotTimeAvailabililyTs()

### ISSUE THREAD

**Issue by sarcusa** [nickmckay/GeoChronR#49]
Hi Nick,

I am using plotTimeAvailabililyTs() and the plot has a weird behavior when one group.var variable contains only one instance. In the image below, see the "wood" category which should be equal to 1, not 170. I checked the LiPD list and only one record contains the wood variable. Everything else looks correct. 

![image](https://user-images.githubusercontent.com/25307765/98172746-1f68bd00-1eaf-11eb-8ef1-eb4fd0258c9c.png)

**Comment by nickmckay** [comment]
Now fixed in version 1.0.5. Details [here](http://nickmckay.github.io/GeoChronR/news/index.html)
