### ISSUE TITLE
Export age ensemble summary

### ISSUE THREAD

**Issue by CommonClimate** [nickmckay/GeoChronR#5]
In many applications, users will want to download a summary of the age ensemble. I propose exporting the timeseries of interest on 5 age models, corresponding  by default to the 2.5%, 24%, 50%, 75%, and 97.5% quantiles *, to a csv or xlsx file. (other quantiles can be passed)
This will encourage users to not restrict themselves to  the median, which would negate using GeoChronR in the first place.

Needs rowQuantiles ffrom the package matrixStats:
https://artax.karlin.mff.cuni.cz/r-help/library/matrixStats/html/rowQuantiles.html

**Comment by nickmckay** [comment]
The methods all produce summaryTables now, and these quantiles are plotted, and customizable. There's not a convenient download option, which we can add if needed.
