### ISSUE TITLE
error installing 

### ISSUE THREAD

**Issue by pblonac** [nickmckay/GeoChronR#52]
this is the error I keep getting when trying to install geoChronR

* installing *source* package ‘zip’ ...
** package ‘zip’ successfully unpacked and MD5 sums checked
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘zip’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/zip’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/zip’
Error: Failed to install 'geoChronR' from GitHub:
  Failed to install 'lipdR' from GitHub:
  (converted from warning) installation of package ‘zip’ had non-zero exit status

**Comment by nickmckay** [comment]
This issue can come up when installing lipdR on Macs, and is typically a git/xcode problem. [This site has a solution of how to fix it](https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a).

**Comment by pblonac** [comment]
Thank you Nick. I managed to make it work. 

bogdan
____________________
Sent from my karst world

Earth without ART is Eh
