### ISSUE TITLE
Errors from Introductory Tutorial

### ISSUE THREAD

**Issue by AndreaLemur** [nickmckay/GeoChronR#53]
Hello,

I am trying to follow the geoChronR tutorial provided [here](http://nickmckay.github.io/GeoChronR/articles/Introduction.html), but keep encountering the following errors when running the provided code:

1. `hulu <- runBchron(hulu,
                  cal.curves = "normal",
                  iter = 10000,
                  extractDate = 10000,
                  which.table = 2,
                  lab.id.var = NULL,
                  age.var = 'age',
                  age.uncertainty.var = 'ageUncertaintyHigh',
                  age.14c.var = NULL,
                  age.14c.uncertainty.var =  NULL,
                  depth.var = 'depth',
                  reservoir.age.14c.var = NULL,
                  reservoir.age.14c.uncertainty.var = NULL,
                  rejected.ages.var = NULL)`
Returns:
`Error in Bchron::Bchronology(ages = cdf$adjustedAges, ageSds = cdf$adjustedAgeUncertainty,  : 
  unused argument (jitterPositions = TRUE)`

2. `hulu$chronData[[1]]$model[[1]]$ensembleTable[[1]]$depth$units <- "mm"
hulu$chronData[[1]]$model[[1]]$ensembleTable[[1]]$depth$variableName <- "position"
chronPlot <- plotChronEns(hulu,truncate.dist = 1e-6)+ggtitle(NULL)+coord_cartesian(xlim = c(80000,30000))`
Returns:
`No variable called ageensemble, or choosing is enforced (always.choose = TRUE)
Cant find any candidates, please select from a list 
1 - depth 
please type the number for the correct match, or a zero if none match: 0
"plotting your chron ensemble. This make take a few seconds..."
Error in xy.coords(x, y, setLab = FALSE) : 'x' and 'y' lengths differ`

From my limited understanding of LiPD, this would suggest that this code is failing to write an ensemble table to the Hulu file. Is this correct? Are there any additions or changes that can be made to this script to fix the issue?

**Comment by nickmckay** [comment]
Hmm,

I'll look into it, it looks like a problem with Bchron, perhaps they've changed something in new version. Can you tell me what version you're running? `packageVersion("Bchron")` should do the trick.

**Comment by nickmckay** [comment]
Yeah, it looks like they've replaced the jitterPositions option - [see details here)[http://andrewcparnell.github.io/Bchron/news/index.html]. This shouldn't break anything in geoChronR, I'll update the tutorial to reflect this change. In the meantime, try removing the `jitterPositions = TRUE` argument and see if you're able to complete the tutorial.

Thanks for alerting us to this!

**Comment by Lydia986** [comment]
I am facing the same problem and am using Bchron version 4.7.6. Could you let me know how to remove the jitterPositions = TRUE argument?

**Comment by nickmckay** [comment]
Hi @Lydia986 , haven't gotten a chance to work on this yet, but to remove that argument, just literally delete `jitterPositions = TRUE` (and any extra commas) from the command

**Comment by nickmckay** [comment]
I've fixed this, and Bchron version >= 4.7.6 should now work as normal. And I was mistaken before, I was thinking we were passing `jitterPositions = TRUE` in the tutorial, but it was actually coded into `runBchron()`, sorry for any confusion.

**Comment by nickmckay** [comment]
To clarify, this is fixed in geoChronR version >= 1.0.11
