### ISSUE TITLE
corEns calling CDF.density function from incorrect namespace

### ISSUE THREAD

**Issue by georgyfalster** [nickmckay/GeoChronR#54]
pvalMonteCarlo currently calls spatstat::CDF.density() but R wants spatstat.core::CDF.density()

Using: R version 4.0.3. Installed spatstat 16th July 2021.

**Comment by nickmckay** [comment]
What version of geoChronR do you have installed? I believe that this issue was fixed in version 1.0.8

**Comment by georgyfalster** [comment]
Oh dang sorry - yep, I have version 1.0.4
