### ISSUE TITLE
lipd file has data shifted in columns

### ISSUE THREAD

**Issue by ekthomas** [nickmckay/GeoChronR#57]
Hi Nick & co,
Not sure if this is a lipd or geochronR issue: I made a lipd file in the playground, exported it, and opened it & started plotting in GeoChronR. A portion of the data have shifted by one column, so I get a nice plot of downcore isotope values, and then a couple sections of the core instead have the analytical uncertainty of the isotope values, which is the neighboring column in the lipd file (see attached fig). When I open the lipd file again in the playground, the columns are indeed shifted. I tried deleting the data from the lipd paleoTable and pasting them in again...had the same issue.
Any thoughts on what's going on, and how to fix? I seem to remember that I had this issue before but can't remember what we did to fix!
Thanks,
Elizabeth
[d2HC28.pdf](https://github.com/nickmckay/GeoChronR/files/7220148/d2HC28.pdf)

**Comment by nickmckay** [comment]
Hmm. I strongly suspect this is an issue with the file and playground. Will you email me the lpd file and I'll take a look? We've had issues if there are commas in string fields (the notes) or with some missing values.

**Comment by ekthomas** [comment]
Aha! I found the issue. One of the columns contains strings (notes about the sediments) and that had commas. The playground was moving text after a comma into the next column. I removed the commas and that fixed the issue. Thanks! Sorry to bug you with this minor thing...
