### ISSUE TITLE
Publication-quality plot of the age ensemble

### ISSUE THREAD

**Issue by CommonClimate** [nickmckay/GeoChronR#6]
Users will want to generate a publication-quality plot like the attached.  Currently the summary plot charts the measured dates as a function of depth, but it doesn’t have error bars; we want those. In addition, we want the 95% highest density region (2.5% to 97.5% quantiles) in light gray and  a few sample paths (10 is good), so that users are reminded that no single path ever looks like the median.

**Comment by CommonClimate** [comment]
@khider and al chatted about this yesterday and agreed that it would be a very nice addition before the GeoChronR workshop.

The idea would be for the plot to adapt to how much info is there: if only calibrated ages vs depth, then keep it barebones. If there are ensemble and distribution tables, use those. It's obviously not as important as a proper documentations, but we're looking forward to re-use that as part of Pyleoclim, and there is no reason to duplicate efforts!  We figured, a plot focused on geochronology should be the purview of GeoChronR.

**Comment by nickmckay** [comment]
Agreed.

This is high on the list.

Thanks for the reminder.

On Tue, May 16, 2017 at 7:27 PM, Julien Emile-Geay <notifications@github.com

**Comment by nickmckay** [comment]
This now exists. It's plotChron(). Room for improvement but it plots a range of probabilities, a handfull of ensemble members, and probability distributions for the ages, if they exist.

**Comment by CommonClimate** [comment]
Fabulous! Thank you

Julien Emile-Geay, associate professor
University of Southern California
http://<https://scholar.google.com/citations?user=OVti4jEAAAAJ&hl=en>climdyn.usc.edu<http://climdyn.usc.edu>



On Aug 14, 2017, at 20:05, Nick McKay <notifications@github.com<mailto:notifications@github.com>> wrote:


This now exists. It's plotChron(). Room for improvement but it plots a range of probabilities, a handfull of ensemble members, and probability distributions for the ages, if they exist.
