### ISSUE TITLE
runOxcal doesn't work with "IntCal20" after update to 1.1.1

### ISSUE THREAD

**Issue by JanPetrik1** [nickmckay/GeoChronR#61]
Hi Nick, runOccal doesn't work with IntCal20 (only for IntCal13) after update.  Thank you.

This is the error: Error in .f(labID = .l[[1L]][[i]], age14C = .l[[2L]][[i]], age14CUnc = .l[[3L]][[i]],  : 
  unrecognized calibration curve: IntCal20

**Comment by nickmckay** [comment]
Indeed,

Thanks for reporting this, I discovered this myself yesterday too. I've
updated the code and am just running some tests and will post a new version
today.

**Comment by nickmckay** [comment]
I think this should be fixed as of 1.1.3
