### ISSUE TITLE
runBacon with multiple types of ages?

### ISSUE THREAD

**Issue by sofiakje** [nickmckay/GeoChronR#63]
Hi Nick!
Is it possible to use multiple types of ages in geoChronR? I want to include a tephra age in an otherwise C14 based chronology, and wonder how to tell geoChronR that this age is already on the cal BP scale? I've added a "cc" column in the chron table in my LiPD file, specifying that cc is 0 for the tephra (=no calibration) and 1 for the ages that should be calibrated with IntCal20, but it doesn't seem like this column is used when running the runBacon command? All ages are still assigned cc=1. 
Thanks,
Sofia

**Comment by nickmckay** [comment]
Yes, there are two ways to do this. The native way is to have two age columns, one for calendar ages (typically called "age") and for radiocarbon ages ("age14C"). And corresponding uncertainty columns ("ageUncertainty" and "age14cUncertainty"). 

Alternatively, you can have a single age column, and an "age_type" column. In that column, use "14C" or "radiocarbon" to distinguish those ages from "tephra" or something else, and geoChronR should handle it properly.

**Comment by sofiakje** [comment]
Ah yes of course, I should have been able to figure that out. Thanks Nick! Sorry to bug you.
