### ISSUE TITLE
reproducibility of age-depth modelling with oxcal

### ISSUE THREAD

**Issue by JanPetrik1** [nickmckay/GeoChronR#64]
Dear Nick,
I'm not sure, if it is issue of GeochronR itself. I have various results of runOxcal function instead of same value of "events.per.unit.length" and "depth.interval". My idea was to use set.seed, but it still produce different models. Is there some solution to have alwayis the same result?

**Comment by nickmckay** [comment]
Hmm, yes, I do not expect `set.seed()` to work for this, since oxcal is running in standalone C code, not R, so it must handle its own random number generation. It may be possible to tell OxCal to do this though, although I don't know how off the top of my head.

**Comment by JanPetrik1** [comment]
Thank you for reply. It could be nice to have an option to have produce same results.
