### ISSUE TITLE
"rejected.ages.var" matched by multiple actual arguments

### ISSUE THREAD

**Issue by JanPetrik1** [nickmckay/GeoChronR#66]
Hello,
all LIPD files with use of argument _rejected.ages.var='rejected'_ give me back the same error:
Error in createChronMeasInputDf(L, ...) : 
  formal argument "rejected.ages.var" matched by multiple actual arguments

Variable name in LIPD files is always _rejected_
I tryed to inpur Nan, TRUE and rejected into the column and nothing work. It is same with runOxcal and runBchron. Is it a bug or I did it wrong?

My code:
Scal<- runOxcal(L, oxcal.path = "~/OxCal/", lab.id.var = 'id', age.var = 'calendarage', age.uncertainty.var = 'calendarageuncertainty', age.14c.var = 'age14c', age.14c.uncertainty.var =  'age14cuncertainty', depth.var = 'depth', reservoir.age.14c.var = 'age correction', reservoir.age.14c.uncertainty.var = NULL, rejected.ages.var = NULL, cal.curve = "IntCal20", rejected.ages.var='rejected', remove.rejected=TRUE)

Thank you, Jan

**Comment by nickmckay** [comment]
I think the issue is that you have both `rejected.ages.var = NULL` and `rejected.ages.var='rejected'` in your command. Delete the first one and it should work.

**Comment by JanPetrik1** [comment]
Yes. I see duplicite arguments. Thank you
