### ISSUE TITLE
R session aborted when installing geoChronR

### ISSUE THREAD

**Issue by sarafransen** [nickmckay/GeoChronR#67]
Hello, when I try to install the geoChronR package I get a notification in a new window saying "R Session Aborted. R encountered a fatal error. The session was terminated." The only option it gives is to start a new session. Some time ago I worked with this package and did not encounter this issue. Do you have an idea what might be going on?

![R fatal error](https://user-images.githubusercontent.com/82447364/169767512-14390830-ba65-4d08-9586-9f3f34b15f0b.jpg)

**Comment by sarafransen** [comment]
Thanks for your reply! 
R version 4.2.0 (2022-04-22 ucrt) -- "Vigorous Calisthenics"
My operating system is Windows (86_64-w64-mingw32/x64 (64-bit))

**Comment by nickmckay** [comment]
OK - the current version of geoChronR seems to be passing the standard installation tests for windows, so it's a not a systematic issue. Are you able to install other packages, using either `remotes::install_github()`or `install.packages()`. Is this specific to geoChronR?

**Comment by sarafransen** [comment]
Yes, I can easily install other packages, so it indeed seems to be specific for geoChronR.

**Comment by nickmckay** [comment]
OK. Does the error happen during any specific step in the installation? I'll see if I can reproduce this and investigate.

**Comment by sarafransen** [comment]
I just realize it happens when I call the geoChronR library, not during installation. When I try

install.packages("nickmckay/geoChronR")

I get this warning:

Installing package into ‘C:/Users/Gebruiker/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘nickmckay/geoChronR’ is not available for this version of R
A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

and when I try

devtools::install_github("nickmckay/geoChronR", subdir = "R", force = TRUE)

I get this:

Downloading GitHub repo nickmckay/geoChronR@HEAD
Error: Failed to install 'geoChronR' from GitHub:
  Does not appear to be an R package (no DESCRIPTION)

and when I leave "force = TRUE" out, I get the following:

Skipping install of 'geoChronR' from a github remote, the SHA1 (1d0299dc) has not changed since last install.
  Use `force = TRUE` to force installation

So from this it seems like the package is installed somewhere, but it does not 'work' with the version of RStudio I'm currently using?

**Comment by sarafransen** [comment]
That seems to work; it installs geoChronR version 1.1.6.
![image](https://user-images.githubusercontent.com/82447364/169907323-bbb38bb8-1902-418a-a5bd-1f5e214a2a8b.png)

**Comment by sarafransen** [comment]
That seems to work fine; geoChronR version 1.1.6 got installed. Though there are still some warning messages:

![image](https://user-images.githubusercontent.com/82447364/169965393-418bfec4-7de0-436b-ba1b-f10e39a5c91c.png)
![image](https://user-images.githubusercontent.com/82447364/169965536-f881bfae-3300-46cd-9c09-c5d517c20993.png)

But when I now load the package (`library(geoChronR)`), the R session gets aborted. So the issue seems to occur when loading the package, rather than installing...

**Comment by sarafransen** [comment]
I now also encouter the 'fatal error' when reading LiPD files into R, using `readLipd()` with and without path argument.
`lipd_read("path argument")` seems to work only for a specific LiPD file which I created recently. Reading LiPD files that I generated last year returns the 'fatal error' message.

**Comment by sarafransen** [comment]
``` r
### 0. INSTALLING REQUISITE PACKAGES AND LOADING LIBRARIES ###

# If not already installed, install packages "remotes" and "devtools"
install.packages("remotes") # To install R packages remotely from Github
#> Installing package into 'C:/Users/Gebruiker/AppData/Local/R/win-library/4.2'
#> (as 'lib' is unspecified)
#> package 'remotes' successfully unpacked and MD5 sums checked
#> 
#> The downloaded binary packages are in
#>  C:\Users\Gebruiker\AppData\Local\Temp\Rtmpi82uFp\downloaded_packages
install.packages("devtools") # Simplifies many common tasks in R, such as setting your working directory wd()
#> Installing package into 'C:/Users/Gebruiker/AppData/Local/R/win-library/4.2'
#> (as 'lib' is unspecified)
#> package 'devtools' successfully unpacked and MD5 sums checked
#> 
#> The downloaded binary packages are in
#>  C:\Users\Gebruiker\AppData\Local\Temp\Rtmpi82uFp\downloaded_packages

install.packages("reprex") # To make reproducible examples of code (see https://reprex.tidyverse.org/)
#> Installing package into 'C:/Users/Gebruiker/AppData/Local/R/win-library/4.2'
#> (as 'lib' is unspecified)
#> package 'reprex' successfully unpacked and MD5 sums checked
#> 
#> The downloaded binary packages are in
#>  C:\Users\Gebruiker\AppData\Local\Temp\Rtmpi82uFp\downloaded_packages
library(reprex)

# Use remotes to install the LiPD Utilities package from Github
remotes::install_github("nickmckay/LiPD-Utilities", subdir = "R", quiet = TRUE)
# Use remotes to install the geoChronR package from Github (used to e.g. identify age model uncertainties)
remotes::install_github("nickmckay/geoChronR")
#> Skipping install of 'geoChronR' from a github remote, the SHA1 (1d0299dc) has not changed since last install.
#>   Use `force = TRUE` to force installation
  
# Call upon the packages you will be using in this script (letting R know which of the installed packages it has to work with)
library(tidyverse) # Contains dplyr for data.frame manipulation and ggplot2 for plotting
library(lipdR) # To read and interact with LiPD data
library(magrittr) # We will be using the magrittr pipe ( %>% ) for simplicity: the outcome of a function is input for the next function
library(geoChronR) # Build around the LiPD data standard, and mostly used for plotting
#> 
#> Attaching package: 'magrittr'
#> The following object is masked from 'package:purrr':
#> 
#>     set_names
#> The following object is masked from 'package:tidyr':
#> 
#>     extract
```

<sup>Created on 2022-06-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

``` r
### 1. READING LIPD DATA INTO THE R WORKSPACE ###

D <- readLipd() # To load the directory that stores all the LiPD files into object "D" (browsing for this directory)
#> Error in readLipd(): could not find function "readLipd"
str(D) # Have a look at the data structure of object "D"
#> function (expr, name)
```

<sup>Created on 2022-06-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
``` r
### 2. PREPARE DATA FOR ANALYSIS AND PLOTTING ###

# 2.1 Extracting data into a time series
#     a time series is a collection of time series objects -> 1 time series object = 1 measurement table column 
TS <- extractTs(D)
#> Error in extractTs(D): could not find function "extractTs"

# 2.2 Have a look at the structure of the time series TS
str(TS)
#> Error in str(TS): object 'TS' not found

# 2.3 Create a tidy data frame: each variable is a column and every observation is a row.
tidyData <- tidyTs(TS, age.var = "age")
#> Error in tidyTs(TS, age.var = "age"): could not find function "tidyTs"
```

<sup>Created on 2022-06-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
``` r
### 3. SOUTHERN OCEAN SST STACK ###

# 3.1 Filter on variables you want to plot.
filterData <- tidyData %>%
  filter(between(age, 350, 450)) %>%                            # Start by selecting all observations with age between 350 and 450 ka 
  filter(interpretation1_variable == "temperature") %>%         # to filter on temperature
  filter(interpretation1_variabledetail == "sea surface") %>%   # to filter on sea surface temperature
  filter(paleoData_variableType == "inferred") %>%              # to filter out proxy measurements (like Mg/Ca) and only include the 'inferred variabledetail' variables, so the calculated SST 
  group_by(dataSetName) %>%                                     # group by dataset name (to cluster records from the same site together)
  arrange(geo_latitude)                                         # and sort by latitude (from top to bottom: low to high lat)
#> Error in tidyData %>% filter(between(age, 350, 450)) %>% filter(interpretation1_variable == : could not find function "%>%"

# 3.1.1 color by dataset name
SST.dataset <- plotTimeseriesStack(filterData,
                                   time.var = "age",
                                   color.var = "dataSetName", # color by dataset name
                                   lab.size = 2,
                                   color.ramp = function(nColors) {     RColorBrewer::brewer.pal(9, "Set1") },
                                   lab.space = 3,
                                   line.size = 0.4,
                                   common.axis = TRUE,
                                   y.axis.range = 4) # determines the vertical 'stretch' of the records; lower value gives larger stretch
#> Error in plotTimeseriesStack(filterData, time.var = "age", color.var = "dataSetName", : could not find function "plotTimeseriesStack"
print(SST.dataset)
#> Error in print(SST.dataset): object 'SST.dataset' not found
```

<sup>Created on 2022-06-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by nickmckay** [comment]
Thanks for posting this. First - over the past couple of years, development in lipdR is happening in a new repository. Soon it will completely supersede the lipd-utilities, but it's ready now. So instead of 

`remotes::install_github("nickmckay/LiPD-Utilities", subdir = "R", quiet = TRUE)`

try 

`remotes::install_github("nickmckay/lipdR")`

and see if that works better.

**Comment by nickmckay** [comment]
That is very strange. I have not had that issue on Windows (or elsewhere). If you skip loading geoChronR can you use lipdR to read in the files?

**Comment by sarafransen** [comment]
Yes, I can read in the lpd files, but not the entire directory - that also gives me the same error. Apparently some of the lpd files cause this error when reading them.

**Comment by nickmckay** [comment]
Would you email or post the files that cause the problem?

**Comment by sarafransen** [comment]
So far I have 4 lpd files that I know of causing the error, which I will e-mail to you. I'm going to try reading in the rest one by one to check if there's more of them.
