### ISSUE TITLE
unreasonable "enter the number of years you'd like to subtract from your data (0 leaves the data unchanged of course) " display

### ISSUE THREAD

**Issue by JanPetrik1** [nickmckay/GeoChronR#70]
Hi Nick, thank you for all the progress with your great geochronR package and all the fedbacks you gave me so far here on github.
I would like to make nice html knit file for my results, but it doesn't allow interactive mode during run of function. Ussually it is not problem, because I can define everything by arguments.

Unfortunatelly I have recently issue with runBacon function. I used all arguments like this:
runBacon (L, lab.id.var = 'id', age.var = 'calendarage', age.uncertainty.var = 'calendarageuncertainty', age.14c.var = 'age14c', age.14c.uncertainty.var =  'age14cuncertainty', depth.var = 'depth', rejected.ages.var = 'rejected', remove.rejected=TRUE, reservoir.age.14c.var = 'age correction', reservoir.age.14c.uncertainty.var = 'age correction uncertainty', cc=1, bacon.acc.mean =10, bacon.thick=5, depths.file=TRUE, seed=1, ask=FALSE, remember=FALSE)

and it ask me anyway this:
enter the number of years you'd like to subtract from your data (0 leaves the data unchanged of course)

I use versin 1.1.6 and all 'age correction' columns are infilled as visible here
<a href="https://imgbb.com/"><img src="https://i.ibb.co/5ct9sr8/V-st-i-ek.jpg" alt="V-st-i-ek" border="0"></a>

Thank you in advance!
Jan

**Comment by nickmckay** [comment]
Hi Jan, funny that you should post this issue as I've been working on this precise issue for my own work. A solution is nearly done already, I will include it in the next version release in the next few days.

**Comment by nickmckay** [comment]
OK,

This should be fixed in 1.1.8. Checkout the changelog for details: https://nickmckay.github.io/GeoChronR/news/index.html
