### ISSUE TITLE
remove rejected does not work with runBacon

### ISSUE THREAD

**Issue by JanPetrik1** [nickmckay/GeoChronR#71]
Dear Nick,
one more issue, but it will be rather my misundertsanding than bug, I will be anyway very happy for help.
I have my script:
runBacon (L, lab.id.var = 'id', age.var = NULL, age.uncertainty.var = NULL, age.14c.var = 'age14c', age.14c.uncertainty.var =  'age14cuncertainty', depth.var = 'depth', reservoir.age.14c.var = NULL, reservoir.age.14c.uncertainty.var = NULL, cc=1, bacon.acc.mean =10, bacon.thick=5, depths.file=TRUE, seed=1, ask=FALSE, remember=FALSE, rejected.ages.var='rejected', remove.rejected=TRUE)

but remove.rejected=TRUE doesn't work and the rejected dates is still there. Here is the view to LIPD table:
<a href="https://imgbb.com/"><img src="https://i.ibb.co/M916VCt/V-st-i-ek.jpg" alt="V-st-i-ek" border="0"></a><br /><a target='_blank' href='https://cs.imgbb.com/'>fotky zdarma</a><br />

Sorry if it is a stupid question and thank you for your attention. Jan

**Comment by JanPetrik1** [comment]
Dear Nick,
here is what is in LIPD table:
<a href="https://ibb.co/6yHhbkT"><img src="https://i.ibb.co/6yHhbkT/img.jpg" alt="img" border="0"></a>

and here is table from bacon:
Added det: NA: 5730.0+-8360000.0 d=117 ResCorr=   0.0+-0.0    a=3 b=4 cc=IntCal20
Added det: UGAMS: 5730.0+-25.0   d=130 ResCorr=   0.0+-0.0    a=3 b=4 cc=IntCal20
Added det: UGAMS53825: 6510.0+-50.0   d=148 ResCorr=   0.0+-0.0    a=3 b=4 cc=IntCal20
Added det: UGAMS52963: 6050.0+-25.0   d=151 ResCorr=   0.0+-0.0    a=3 b=4 cc=IntCal20
Added det: UGAMS52962: 6440.0+-30.0   d=167.8 ResCorr=   0.0+-0.0    a=3 b=4 cc=IntCal20
Added det: UGAMS53824: 7100.0+-30.0   d=180 ResCorr=   0.0+-0.0    a=3 b=4 cc=IntCal20
Added det: UGAMS19700: 6780.0+-30.0   d=197.5 ResCorr=   0.0+-0.0    a=3 b=4 cc=IntCal20
Added det: UGAMS53467: 7570.0+-30.0   d=202 ResCorr=  88.0+-0.0    a=3 b=4 cc=IntCal20
Added det: UGAMS: 7300.0+-30.0   d=215 ResCorr=   0.0+-0.0    a=3 b=4 cc=IntCal20
Added det: UGAMS: 7400.0+-30.0   d=270 ResCorr=   0.0+-0.0    a=3 b=4 cc=IntCal20
Added det: UGAMS: 8360.0+-30.0   d=380 ResCorr=   0.0+-0.0    a=3 b=4 cc=IntCal20

**Comment by nickmckay** [comment]
Yep, I found the bug. There was a bug that made the remove.rejected option not work when there was exactly one rejected age. It is now fixed in 1.1.9

Thanks for reporting!

**Comment by JanPetrik1** [comment]
My pleasure
