### ISSUE TITLE
Error in if (is.na(bacon.acc.mean)) { : the condition has length > 1 when bacon.acc.mean=c()

### ISSUE THREAD

**Issue by istvan60** [nickmckay/GeoChronR#74]
When I try to apply different accumulation rates to a record (on R 4.2.1 on Mac OS 13.0)
[Vacska03.lpd.zip](https://github.com/nickmckay/GeoChronR/files/10057923/Vacska03.lpd.zip) 
before and after a break

```
L <- runBacon(L,
              lab.id.var = 'sample code', 
              cc=0,
              age.var = 'U-Th age',
              d.min=0,
              d.max=152,
              depth.unit="mm",
              age.uncertainty.var = 'ageUnc',
              depth.var = 'dft', 
              rejected.ages.var = NULL,
              boundary = 48,
              accept.suggestions = F,
              bacon.acc.mean	=c(10,20) ,
              acc.shape	=c(1.5,2) ,
              mem.mean=0.65,
              close.connection = T)
```

 the function gives the following error 
`Error in if (is.na(bacon.acc.mean)) { : the condition has length > 1 `

If I do not fiddle with the varying accumulation rate, 
```
bacon.acc.mean	=20 ,
acc.shape	=1.5 ,
```
everything works fine, although it obviously need some fine tuning regarding the parameters.
<img width="669" alt="Screenshot 2022-11-21 at 16 50 24" src="https://user-images.githubusercontent.com/20128185/203098722-ca6dbbf4-8a8e-457e-a453-2a093d809321.png">
This warning is usually thrown when the condition in a conditional statement is a vector rather than a single value, which is obvious since I want to use two priors for acc.mean() 10 and 20, one before and one after the boundary. May this be a bug or am I missing something?

Thank you!

**Comment by nickmckay** [comment]
Ah yes, this is a common bug that showed up after the upgrade to R 4.2 . I'll take a look and try to fix it today.

**Comment by istvan60** [comment]
Indeed I am using R 4.2.1 on Mac OS 13.0

**Comment by istvan60** [comment]
@nickmckay may I ask, did you manage to solve the issue, or for the time being, should I install a previous R version? Thank you!

**Comment by nickmckay** [comment]
Hi, sorry, no I have not had time to fix this yet.  It should be a fairly quick fix, but we'll want to test it to make sure there are no unintended effects. I'm hoping to get to this next week, so if it's urgent, stepping down to <4.2 should help.

**Comment by istvan60** [comment]
It works like a charm in 1.1.10 under R 4.2.1. Thank you for the update!

**Comment by nickmckay** [comment]
Great! Let me know if you run into any trouble.
