### ISSUE TITLE
Binning in corEns only the climate data, is it possible? Enhancement

### ISSUE THREAD

**Issue by istvan60** [nickmckay/GeoChronR#75]
When on is running the Ensemble correlation with the `corEns ` function there is no opportunity to bin only the used climate data and leave the proxy as it is. In the example below the proxy is already quite smooth, so there is no sense in removing more high-frequency variability. The aim would be to fit the resolution of the instrumental data to  the proxy, i.e. find a binning for the instrumental which provides the best correspondence with the proxy.

![kép](https://user-images.githubusercontent.com/20128185/213132982-1aba7a22-a9f6-416d-ad76-5b66b90d3683.png)

Thanks for your consideration.

**Comment by nickmckay** [comment]
Hmm, I'm not sure I understand. In `corEns()` you specify the `bin.vec` or `bin.step` that you want for both series. You can choose the resolution that makes the most sense for the two datasets. Also remember that in the case there is more variability in the proxy ensemble members than you see in the median. 

Ultimately, to correlate, the two timeseries have to be aligned. Binning is the primary strategy we use in geoChronR to achieve this. There are other strategies, like interpolation or curve fitting, that could be used, and that we've discussed adding. Is this what you're looking for?
