### ISSUE TITLE
Error installing GeoChronR

### ISSUE THREAD

**Issue by ekthomas** [nickmckay/GeoChronR#80]
Hi Nick! 
I have a new comp (a Mac), with the latest version of R and RStudio and am installing geoChronR for the first time on this machine. I got the below error message. So far, I have tried (and got the same message):

- restarting everything, including comp
- when prompted with options to install updated versions of packages, I've tried installing ALL packages, CRAN only, and None

Sorry if it's a silly/easy fix, thanks for your help!
Elizabeth

ERROR: lazy loading failed for package ‘geoChronR’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/geoChronR’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/5z/d18gfz9n2d1ffs0620jtvcxm0000gn/T//Rtmp1JYCnL/file848468fb5f4/geoChronR_1.1.10.tar.gz’ had non-zero exit status

**Comment by ekthomas** [comment]
I'm using this install command: devtools::install_github("nickmckay/GeoChronR", force = TRUE)
and the version of R: R 4.3.1 GUI 1.79 Big Sur ARM build
RStudio: 2023.09.1+494

**Comment by nickmckay** [comment]
Definitely a not a silly message, this was the first of three times I heard about this error this week. I'm not 100% certain that yours is the same, but I suspect that this is related to the rEDM package deciding to change it's function names :(. I've pushed an update (1.1.11) that I think fixes it. Will you try to install it again and let me know if it works?

**Comment by ekthomas** [comment]
Yes, this worked! Thanks Nick :)
