### ISSUE TITLE
issues with pcaMethods when installing geoChronR 

### ISSUE THREAD

**Issue by routson** [nickmckay/GeoChronR#85]
I was getting repeated errors attempting to install geoChronR. Many warning and error messages, but the issue appeared to be with accessing pcaMethods. 

I found a workaround by installing pcaMethods separately with the following prompt:  > BiocManager::install("pcaMethods"). There was an old bug in 2018 reported that led me to this solution.

Before installing pcaMethods I ran the following, but I'm not sure it was necessary and didn't solve the issue on its own: > BiocManager::install("biocLite")

I'm using rstudio version 2024.04.1+748 and R version 4.4.0

**Comment by nickmckay** [comment]
Hmm, that should install automatically as set up, but I'll see if I can replicate this
