### ISSUE TITLE
Error in .make_numeric_version(x, strict, .standard_regexps()$valid_numeric_version) when running runBacon()

### ISSUE THREAD

**Issue by mat1506** [nickmckay/GeoChronR#86]
I encountered an error while running the runBacon() function from the geoChronR package. The error message is:

"Error in .make_numeric_version(x, strict, .standard_regexps()$valid_numeric_version) : invalid non-character version specification 'x' (type: double)"

I am working on a project that involves using the runBacon() function to process chronological data. Here are the details of my setup:

Operating System: Linux Ubuntu 22.04.4 LTS
R Version: Ubuntu 22.04.4 LTS
geoChronR Version: geoChronR 1.1.12
rbacon Version: rbacon 3.2

Thank you so much for your help!

**Comment by mat1506** [comment]
Hi,

I wanted to update you all that I managed to resolve the problem by installing an older version of R (specifically R 4.3).

**Comment by nickmckay** [comment]
Thanks for reporting. I suspect that this is actually a problem with the lipdR dependency, as they changed how numeric_version works. I've updated that package, so hopefully this will work well with future versions of R will work. I'll close when I've confirmed it works.

**Comment by nickmckay** [comment]
This should be fixed as of version 1.1.14
