### ISSUE TITLE
GeoChronR installation

### ISSUE THREAD

**Issue by sudipacharya22** [nickmckay/GeoChronR#87]
I tried to install geoChronR using
<- remotes::install_github("nickmckay/geoChronR")
outcome: 
Installing package into ‘.../Local/R/win-library/4.4’
(as ‘lib’ is unspecified)
ERROR: dependencies 'pcaMethods', 'lipdR' are not available for package 'geoChronR'
* removing '.............../Local/R/win-library/4.4/geoChronR'
Warning messages:
1: In i.p(...) :
  installation of package ‘....../Local/Temp/RtmpsLyB3Y/file8c03d63926/lipdR_0.5.6.tar.gz’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘......../Local/Temp/RtmpsLyB3Y/file8c052c049ec/geoChronR_1.1.12.tar.gz’ had non-zero exit status

after this when i use 
<- library(geoChronR)

Error in library(geoChronR) : there is no package called ‘geoChronR’

I don't know what the problem is, is there anyone who can help me.

**Comment by nickmckay** [comment]
It looks like lipdR and pcaMethods are not installing properly. They should install automatically, but you could try installing them separately. 

`remotes::install_github("nickmckay/lipdR")`

and 

```
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("pcaMethods")
```
