### ISSUE TITLE
‘Error in if (a > 0) { : missing value where TRUE/FALSE needed’ when running ‘corEns’ function

### ISSUE THREAD

**Issue by LauraStreib** [nickmckay/GeoChronR#89]
Hello,

I am receiving the error message ‘Error in if (a > 0) { : missing value where TRUE/FALSE needed’ on certain dataset pairs when running the ‘corEns’ function. Many datasets run just fine, but certain combinations of datasets return the error message (e.g. A will run with B, and B will run with C, but A and C return the error message). The error message is also returned when trying different bin sizes, one dataset pairing returns this error when bins are smaller than 4,500 year and another returns the error when bins are larger than 2,500 years. I have tried creating fresh LiPD files many times and sometimes this fixes the problem, but some pairings return the error no matter how many LiPD files I try. Do you know what is causing this error or how I can get around it?

Thank you for your help.

**Comment by nickmckay** [comment]
Sorry for the delay on this one. 

I'm not certain why some of your datasets are throwing this error - most of the obvious causes should be caught upstream by other error messages. I added in some additional error checks in version 1.1.14, which might be helpful. If the new error messages don't help, if you could send me an RData file with an example of two datasets that give this error, I can reproduce it and then fix it.

**Comment by nickmckay** [comment]
OK, I think I actually resolved this in 1.1.15. Please update and let me know if you run into additional issues.
